openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Users API'
  description: API
servers:
  - url: http://localhost:8080
    description: Example server
paths:
  /search:
    get:
      summary: Поиск пользователей по маске имени и фамилии
      parameters:
      - name: first_name
        description: Имя
        in: query
        required: true
        schema:
          type: string
      - name: last_name
        description: Фамилия
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The users for the provided masks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'
        404:
          description: No user found for the provided mask
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth:
    get:
      summary: Проверка аутентификации
      responses:
        '200':
          description: User ID
          content:
            application/json:
              schema:
               type: string
        401:
          description: Not authentication
          content:
            application/json:
              schema:
                type: string
  /user:
    get:
      summary: Чтение информации о пользователе
      parameters:
      - name: id
        description: Уникальный идентификатор пользователя
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/user_id'
      responses:
        '200':
          description: Найденный пользователь
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        404:
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Добавление нового пользователя
      parameters:
      - name: first_name
        description: Имя пользователя
        in: query
        required: true
        schema:
          type: string
      - name: last_name
        description: Фамилия пользователя
        in: query
        required: true
        schema:
          type: string
      - name: email
        description: email пользователя
        in: query
        required: true
        schema:
          type: string
      - name: login
        description: login пользователя
        in: query
        required: true
        schema:
          type: string
      - name: password
        description: пароль пользователя
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Идентификатор, добавленного пользователя
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /showlist:
    get:
      summary: Вывести список всех продуктов
      responses:
        '200':
          description: The users for the provided masks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/products'
        404:
          description: No user found for the provided mask
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /product:
    post:
      summary: Добавление нового продукта
      parameters:
      - name: name
        description: Название продукта
        in: query
        required: true
        schema:
          type: string
      - name: category
        description: Категория продукта
        in: query
        required: true
        schema:
          type: string
      - name: method
        description: Способ получения продукта
        in: query
        required: true
        schema:
          type: string
      - name: description
        description: Описание продукта
        in: query
        required: true
        schema:
          type: string
      - name: presence
        description: Описание продукта
        in: query
        required: true
        schema:
          type: string
      - name: price
        description: Цена продукта
        in: query
        required: true
        schema:
          type: string
      - name: user_id
        description: идентификатор пользователя
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Идентификатор, добавленного продукта
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления продукта
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /getbasket:
    get:
      summary: Поиск корзины по маске ID пользователя
      parameters:
      - name: user_id
        description: идентификатор пользователя
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: The product for the provided masks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/basket'
        404:
          description: No user found for the provided mask
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /basket:
    post:
      summary: Добавление продукта в корзину
      parameters:
      - name: user_id
        description: идентификатор пользователя
        in: query
        required: true
        schema:
          type: integer
      - name: product_id
        description: идентификатор продукта
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Идентификатор, добавленного продукта
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления продукта
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    user_id:
      description: Уникальный идентификатор пользователя
      type: integer
    users:
      type: array
      items:
        $ref: '#/components/schemas/user'
    user:
      type: object
      required:
        - id
        - first_name
        - last_name
        - email
        - login
        - password
      properties:
        id:
          $ref: '#/components/schemas/user_id'
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        login:
          type: string
        password:
          type: string
    product_id:
      description: Уникальный идентификатор продукта
      type: integer
    products:
      type: array
      items:
        $ref: '#/components/schemas/product'
    product:
      type: object
      required:
        - id
        - name
        - category 
        - method
        - desctiption
        - presence
        - price
        - user_id
      properties:
        id:
          $ref: '#/components/schemas/product_id'
        name:
          type: string
        category:
          type: string
        method:
          type: string
        description:
          type: string
        presence:
          type: string
        price:
          type: string
        user_id:
          type: integer
    basket_id:
      description: Уникальный идентификатор заказа
      type: integer
    baskets:
      type: array
      items:
        $ref: '#/components/schemas/basket'
    basket:
      type: object
      required:
        - id
        - user_id
        - product_id
      properties:
        id:
          $ref: '#/components/schemas/basket_id'
        user_id:
          type: integer
        product_id:
          type: integer
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string
  securitySchemes:
      basicAuth:     
        type: http
        scheme: basic
security:
  - basicAuth: []