openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'API BasketService'
  description: API для работы с корзиной
servers:
  - url: http://localhost:8082
    description: Basket server
paths:
  /add_product:
    post:
      summary: Добавление товара в корзину
      parameters:
      - name: user_id
        description: Уникальный идентификатор заказчика
        in: query
        required: true
        schema:
          type: integer
      - name: product_id
        description: Уникальный идентификатор услуги
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: The product was added
        404:
          description: Error with adding the product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /get_basket:
    get:
      summary: Получение корзины пользователя
      parameters:
      - name: user_id
        description: Уникальный идентификатор заказчика
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: The basket was gotten
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/baskets'
        404:
          description: Error with getting the basketr
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    baskets:
      type: array
      items:
        $ref: '#/components/schemas/basket'
    basket:
      type: object
      required:
        - user_id
        - product_id
      properties:
        user_id:
          type: integer
        product_id:
          type: integer
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string
  securitySchemes:
      basicAuth:     
        type: http
        scheme: basic
security:
  - basicAuth: []